name: Rupert Qin
description: Javascript and Elixir Full Stack developer in China
encoding: UTF-8
# highlighter: pygments
highlighter: rouge
relative_permalinks: false
permalink: /:categories/:title/
port: 5001
paginate: 15
paginate_path: "list/:num"
gems: [jekyll-paginate]